# Generated by Django 2.0.5 on 2018-05-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC_IF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_NAME', models.CharField(max_length=200)),
                ('C_NUMBER', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deal_IF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AC_ID', models.IntegerField(default=0)),
                ('DEAL_DATE', models.DateTimeField(verbose_name='Date of transaction')),
                ('ITEM_ID', models.IntegerField(default=0)),
                ('BUY_CT', models.IntegerField(default=0)),
                ('BUY_AM', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200)),
                ('PRICE', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='S_IF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_NAME', models.CharField(max_length=200)),
                ('NAME', models.CharField(max_length=200)),
                ('INDUSTRY', models.CharField(max_length=200)),
                ('EVENT', models.CharField(max_length=200)),
                ('ADDRESS', models.CharField(max_length=200)),
                ('TEL', models.CharField(max_length=200)),
            ],
        ),
    ]
